In [1]:
import pandas as pd

df1 = pd.read_csv('diabetes.csv')
df1.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [2]:
x = df1.iloc[:, 0:8]
y = df1.iloc[:, 8]

x.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33

In [3]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [4]:
df1.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [5]:
from keras.models import Sequential
from keras.layers import Dense

In [6]:
m1 = Sequential()
m1.add(Dense(12, input_dim=8, activation='relu'))
m1.add(Dense(8, activation='relu'))
m1.add(Dense(1, activation='sigmoid'))

In [7]:
m1.compile(loss='binary_crossentropy', optimizer='adam', metrics='accuracy')

In [8]:
m1.fit(x, y, epochs=60, batch_size=10)

Epoch 1/60
 1/77 [..............................] - ETA: 0s - loss: 27.5005 - accuracy: 0.4000WARNING:tensorflow:Callbacks method `on_train_batch_end` is slow compared to the batch time (batch time: 0.0000s vs `on_train_batch_end` time: 0.0010s). Check your callbacks.
77/77 [==============================] - 0s 652us/step - loss: 13.7366 - accuracy: 0.3529
Epoch 2/60
77/77 [==============================] - 0s 640us/step - loss: 1.2273 - accuracy: 0.5833
Epoch 3/60
77/77 [==============================] - 0s 703us/step - loss: 1.0284 - accuracy: 0.6211
Epoch 4/60
77/77 [==============================] - 0s 702us/step - loss: 0.9516 - accuracy: 0.6237
Epoch 5/60
77/77 [==============================] - 0s 630us/step - loss: 0.9042 - accuracy: 0.6107
Epoch 6/60
77/77 [==============================] - 0s 628us/step - loss: 0.8531 - accuracy: 0.6302
Epoch 7/60
77/77 [==============================] - 0s 681us/step - loss: 0.8268 - accuracy: 0.6276
Epoch 8/60
77/77 [==============================] - 0s 610us/step - loss: 0.7887 - accuracy: 0.6354
Epoch 9/60
77/77 [==============================] - 0s 701us/step - loss: 0.7613 - accuracy: 0.6341
Epoch 10/60
77/77 [==============================] - 0s 675us/step - loss: 0.7342 - accuracy: 0.6445
Epoch 11/60
77/77 [==============================] - 0s 636us/step - loss: 0.7125 - accuracy: 0.6497
Epoch 12/60
77/77 [==============================] - 0s 727us/step - loss: 0.6941 - accuracy: 0.6576
Epoch 13/60
77/77 [==============================] - 0s 675us/step - loss: 0.6789 - accuracy: 0.6432
Epoch 14/60
77/77 [==============================] - 0s 662us/step - loss: 0.6782 - accuracy: 0.6719
Epoch 15/60
77/77 [==============================] - 0s 623us/step - loss: 0.6463 - accuracy: 0.6927
Epoch 16/60
77/77 [==============================] - 0s 636us/step - loss: 0.6477 - accuracy: 0.6810
Epoch 17/60
77/77 [==============================] - 0s 649us/step - loss: 0.6417 - accuracy: 0.6706
Epoch 18/60
77/77 [==============================] - 0s 610us/step - loss: 0.6457 - accuracy: 0.6836
Epoch 19/60
77/77 [==============================] - 0s 714us/step - loss: 0.6196 - accuracy: 0.6953
Epoch 20/60
77/77 [==============================] - 0s 610us/step - loss: 0.6210 - accuracy: 0.6810
Epoch 21/60
77/77 [==============================] - 0s 610us/step - loss: 0.6076 - accuracy: 0.6979
Epoch 22/60
77/77 [==============================] - 0s 675us/step - loss: 0.6046 - accuracy: 0.6823
Epoch 23/60
77/77 [==============================] - 0s 636us/step - loss: 0.6029 - accuracy: 0.6862
Epoch 24/60
77/77 [==============================] - 0s 597us/step - loss: 0.6164 - accuracy: 0.6810
Epoch 25/60
77/77 [==============================] - 0s 610us/step - loss: 0.6031 - accuracy: 0.6784
Epoch 26/60
77/77 [==============================] - 0s 805us/step - loss: 0.6036 - accuracy: 0.6927
Epoch 27/60
77/77 [==============================] - 0s 649us/step - loss: 0.5816 - accuracy: 0.7109
Epoch 28/60
77/77 [==============================] - 0s 597us/step - loss: 0.5864 - accuracy: 0.7174
Epoch 29/60
77/77 [==============================] - 0s 558us/step - loss: 0.5933 - accuracy: 0.7161
Epoch 30/60
77/77 [==============================] - 0s 649us/step - loss: 0.5941 - accuracy: 0.6979
Epoch 31/60
77/77 [==============================] - 0s 623us/step - loss: 0.5812 - accuracy: 0.7083
Epoch 32/60
77/77 [==============================] - 0s 597us/step - loss: 0.5683 - accuracy: 0.7253
Epoch 33/60
77/77 [==============================] - 0s 597us/step - loss: 0.5751 - accuracy: 0.7214
Epoch 34/60
77/77 [==============================] - 0s 623us/step - loss: 0.5662 - accuracy: 0.7305
Epoch 35/60
77/77 [==============================] - 0s 623us/step - loss: 0.5826 - accuracy: 0.7214
Epoch 36/60
77/77 [==============================] - 0s 610us/step - loss: 0.5598 - accuracy: 0.7148
Epoch 37/60
77/77 [==============================] - 0s 584us/step - loss: 0.5632 - accuracy: 0.7096
Epoch 38/60
77/77 [==============================] - 0s 571us/step - loss: 0.5707 - accuracy: 0.7344
Epoch 39/60
77/77 [==============================] - 0s 571us/step - loss: 0.5632 - accuracy: 0.7344
Epoch 40/60
77/77 [==============================] - 0s 597us/step - loss: 0.5538 - accuracy: 0.7305
Epoch 41/60
77/77 [==============================] - 0s 623us/step - loss: 0.5649 - accuracy: 0.7292
Epoch 42/60
77/77 [==============================] - 0s 597us/step - loss: 0.5600 - accuracy: 0.7148
Epoch 43/60
77/77 [==============================] - 0s 623us/step - loss: 0.5684 - accuracy: 0.7083
Epoch 44/60
77/77 [==============================] - 0s 584us/step - loss: 0.5614 - accuracy: 0.7174
Epoch 45/60
77/77 [==============================] - 0s 584us/step - loss: 0.5656 - accuracy: 0.7253
Epoch 46/60
77/77 [==============================] - 0s 610us/step - loss: 0.5628 - accuracy: 0.7109
Epoch 47/60
77/77 [==============================] - 0s 584us/step - loss: 0.5416 - accuracy: 0.7383
Epoch 48/60
77/77 [==============================] - 0s 597us/step - loss: 0.5509 - accuracy: 0.7305
Epoch 49/60
77/77 [==============================] - 0s 597us/step - loss: 0.5495 - accuracy: 0.7227
Epoch 50/60
77/77 [==============================] - 0s 584us/step - loss: 0.5510 - accuracy: 0.7070
Epoch 51/60
77/77 [==============================] - 0s 584us/step - loss: 0.5531 - accuracy: 0.7083
Epoch 52/60
77/77 [==============================] - 0s 571us/step - loss: 0.5441 - accuracy: 0.7435
Epoch 53/60
77/77 [==============================] - 0s 571us/step - loss: 0.5432 - accuracy: 0.7435
Epoch 54/60
77/77 [==============================] - 0s 584us/step - loss: 0.5463 - accuracy: 0.7370
Epoch 55/60
77/77 [==============================] - 0s 558us/step - loss: 0.5444 - accuracy: 0.7331
Epoch 56/60
77/77 [==============================] - 0s 545us/step - loss: 0.5407 - accuracy: 0.7318
Epoch 57/60
77/77 [==============================] - 0s 558us/step - loss: 0.5474 - accuracy: 0.7214
Epoch 58/60
77/77 [==============================] - 0s 571us/step - loss: 0.5513 - accuracy: 0.7148
Epoch 59/60
77/77 [==============================] - 0s 597us/step - loss: 0.5414 - accuracy: 0.7422
Epoch 60/60
77/77 [==============================] - 0s 558us/step - loss: 0.5336 - accuracy: 0.7344

In [9]:
_, accuracy = m1.evaluate(x, y)
print ('Accuracy: %.2f' % (accuracy*100))

24/24 [==============================] - 0s 1ms/step - loss: 0.5231 - accuracy: 0.7435
Accuracy: 74.35

In [10]:
# pred1 = m1.predict_classes(x)  --> the original code in Lesson 4 but resulting warning gave below code 

pred1 = (m1.predict(x) > 0.5).astype("int32")
pred1[0:5]

array([[1],
       [0],
       [1],
       [0],
       [0]])

In [11]:
df1['Outcome'].head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64